version: 2.1

jobs:
  build-images:
    docker:
      - image: circleci/python:3.8  # Use an image that includes Docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Adjust Docker version as needed
          docker_layer_caching: true
      - run:
          name: Build Docker images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t sreedocker123/mompopcafeapp:circleci ./mompopcafe
            docker build -t sreedocker123/mompopdb:circleci ./mompopdb
      - persist_to_workspace:
          root: .
          paths:
            - /tmp/docker-images

  push-images:
    docker:
      - image: circleci/python:3.8  # Use an image that includes Docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Adjust Docker version as needed
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/docker-images
      - run:
          name: Push Docker images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push sreedocker123/mompopcafeapp:circleci
            docker push sreedocker123/mompopdb:circleci

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-images
      - push-images:
          requires:
            - build-images
